#!/usr/bin/env node
/**
 * Run one trial end to end: materialize, launch the agent behind the isolation
 * boundary, then evaluate.
 *
 * The two halves run in different places. Materializing and evaluating are
 * controller work and need no privileges; launching the agent needs Docker, and
 * the controller container deliberately has no Docker client. So the default
 * flow is two phases:
 *
 *   node scripts/run-trial.mjs control-plane-001            # prepare
 *   sh  /data2/kexiao/EvoCFD/runs/<id>/run-agent.sh          # on the host
 *   node scripts/run-trial.mjs control-plane-001 --judge     # verdict
 *
 * `--fake` replaces the agent with a deterministic prober that applies the
 * intended fix, which makes the whole pipeline provable without spending a model
 * call. The real path is the same plumbing with a different command; it runs the
 * agent runtime mounted read-only, with its session directory on /agent-state
 * and the prompt read from the mounted task file.
 *
 * Usage: node scripts/run-trial.mjs <fixture-id> [--fake] [--judge] [--trial-id <id>]
 */
import { spawnSync } from "node:child_process";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { buildAgentContainer, evaluateTrial, loadFixture, loadMaterializedTrial, materializeFixture } from "../packages/controller/src/index.ts";

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
// The controller sees the repository at a different path than the host does;
// mount sources must be host paths. See scripts/verify-isolation.mjs.
const HOST_ROOT = process.env.EVOCFD_HOST_ROOT ?? REPO_ROOT;
const RUNS_DIR = join(REPO_ROOT, "runs");
const SCRIPTS_DIR = join(HOST_ROOT, "scripts");
const FIXTURE_ROOT = join(REPO_ROOT, "fixtures");
const IMAGE = "evocfd-dev:node22";
const FIXTURE_ID = process.argv[2] ?? "control-plane-001";
const MODE_FAKE = process.argv.includes("--fake");
const MODE_JUDGE = process.argv.includes("--judge");
const TRIAL_ID = argValue("--trial-id") ?? `${FIXTURE_ID}-trial-001`;
const AGENT_RUNTIME = process.env.EVOCFD_AGENT_RUNTIME ?? "/data2/kexiao/.pi-agent";

function argValue(name: string): string | undefined {
  const index = process.argv.indexOf(name);
  return index === -1 || index + 1 >= process.argv.length ? undefined : process.argv[index + 1];
}

const stateDir = join(RUNS_DIR, "agent-state", TRIAL_ID);

if (!MODE_JUDGE) {
  const fixture = await loadFixture(join(FIXTURE_ROOT, FIXTURE_ID));
  await mkdir(stateDir, { recursive: true });
  const trial = await materializeFixture({ fixture, trialId: TRIAL_ID, runsDir: RUNS_DIR });
  console.log(`materialized ${TRIAL_ID} at ${trial.layout.root}`);

  const launch = buildAgentContainer(
    {
      trialRoot: join(HOST_ROOT, "runs", TRIAL_ID),
      rsihDir: join(HOST_ROOT, "third_party", "RSI-Harness"),
      agentStateDir: join(HOST_ROOT, "runs", "agent-state", TRIAL_ID),
      agentRuntimeDir: MODE_FAKE ? undefined : AGENT_RUNTIME,
      uid: 1001,
      gid: 1001,
    },
    IMAGE,
  );

  // What the agent is asked to do. The prompt is read inside the container from
  // the mounted task file, so nothing about the task has to be duplicated here.
  const command = MODE_FAKE
    ? ["node", "/prober/fake-agent.mjs", "/task/workspace"]
    : [
        "sh",
        "-c",
        `exec node /agent-runtime/dist/bundle/cli.js --mode json --print --no-session ` +
          `--no-extensions --no-skills --no-context-files --no-tools ` +
          `--provider evocfd-intern-ai "$(cat /task/TASK.md)"`,
      ];
  const extra = MODE_FAKE
    ? ["-v", `${join(SCRIPTS_DIR, "fake-agent.mjs")}:/prober/fake-agent.mjs:ro`]
    : ["-e", `PI_CODING_AGENT_DIR=/agent-state`];

  const argv = ["docker", "run", ...extra, ...launch.args, ...command];
  const script = [
    "#!/bin/sh",
    "# Generated by scripts/run-trial.ts — do not edit.",
    "# Runs the agent for the trial in its isolated container.",
    `# agent: ${MODE_FAKE ? "deterministic fake" : "real pi"}`,
    "",
    "set -e",
    `exec ${argv.map((a) => `'${a.replaceAll("'", "'\\''")}'`).join(" ")}`,
    "",
  ].join("\n");
  await writeFile(join(trial.layout.root, "run-agent.sh"), script, { mode: 0o755 });

  if (MODE_FAKE) {
    const probe = spawnSync("docker", ["version", "--format", "{{.Client.Version}}"], { windowsHide: true });
    if (probe.status === 0) {
      spawnSync("sh", [join(trial.layout.root, "run-agent.sh")], { stdio: "inherit", windowsHide: true });
    } else {
      console.log("docker client unavailable here — run the agent on the compute host:\n");
      console.log(`  sh ${join(HOST_ROOT, "runs", TRIAL_ID, "run-agent.sh")}\n`);
      console.log("then judge it with:");
      console.log(`  node scripts/run-trial.ts ${FIXTURE_ID} --judge --trial-id ${TRIAL_ID}`);
      process.exit(0);
    }
  }
}

if (MODE_JUDGE || MODE_FAKE) {
  const trial = await loadMaterializedTrial(RUNS_DIR, TRIAL_ID);
  const result = await evaluateTrial(trial);
  console.log("");
  console.log(`trial      ${result.trial_id}`);
  console.log(`verdict    ${result.pass ? "PASS" : "FAIL"}`);
  if (result.error) console.log(`error      ${result.error}`);
  for (const criterion of result.criteria) {
    console.log(`  ${criterion.pass ? "pass" : "fail"}  ${criterion.criterion} — ${criterion.detail}`);
  }
  console.log(`identity   ${result.trial_identity}`);
  process.exitCode = result.pass ? 0 : 1;
}
