/**
 * Runs one real CFD job through the job-lifecycle primitive.
 *
 * Two phases, because the solver and the controller cannot run in the same
 * place. The controller is a Node toolchain in the campaign container; the
 * solver was built on the host against system gcc and system Open MPI and links
 * libmpi.so.40, which the container does not provide. Mounting the host
 * binaries into the container does not make them runnable there — the loader
 * error is genuine, and rebuilding the solver inside a container would be a
 * second, differently-identified build rather than a fix for this one.
 *
 * So the boundary is explicit and the two phases are separate processes:
 *
 *   plan   (container)  records the write-once plan and the runner script
 *   run    (host)       executes the runner, where the libraries are
 *   assess (container)  reads the log back and updates the record
 *
 * Nothing is hidden: the plan is recorded before anything runs, the executed
 * command is the one the plan recorded, and the assessment reads only what the
 * solver wrote. The agent never sees the docker socket and never invokes the
 * solver; both are controller capabilities.
 *
 * Usage:
 *   node scripts/run-cfd-job.ts plan
 *   node scripts/run-cfd-job.ts run <job-dir>     # on the host
 *   node scripts/run-cfd-job.ts assess <job-dir>
 */
import { join } from "node:path";
import { mkdir, cp, rm, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";

import {
  buildCommand,
  planDigest,
  readJobRecord,
  readLastTime,
  readTerminatedNormally,
  resolveProfile,
  updateJobState,
  writeJobRecord,
} from "../packages/controller/src/cfd-exec.ts";
import type { CfdJobPlan, CfdJobState } from "../packages/controller/src/cfd-job.ts";

const JOB_ID = "1D-advection-001";
const RUNNER = "run.sh";
const LOG_FILE = "log.react";

function makeProfile(): ReturnType<typeof resolveProfile> {
  return resolveProfile({
    id: "of8-realfluid",
    executable: "/data2/kexiao/of8/rf-profile/bin/reactingFoam",
    executableSha256:
      "14fd124a0e46d043cdad5f9b6b8e26ed23d0778084d55c609e9665d58799007c",
    envFile: "/data2/kexiao/of8/rf-profile-env.sh",
    libraryPaths: [
      "/data2/kexiao/of8/rf-profile/lib",
      "/data2/kexiao/of8/OpenFOAM-8/platforms/linux64GccDPInt32Opt/lib",
    ],
    expectedProfileLibraries: [
      "libreactionThermophysicalModels.so",
      "libspecie.so",
      "libchemistryModel.so",
      "libcombustionModels.so",
    ],
  });
}

function makePlan(jobDir: string): CfdJobPlan {
  return {
    jobId: JOB_ID,
    profile: makeProfile(),
    caseDir: jobDir,
    args: [],
    budgetSeconds: 600,
    requestedEndTime: 0.002,
    ranks: 1,
    logFile: LOG_FILE,
  };
}

function emptyState(jobId: string): CfdJobState {
  return {
    jobId,
    state: "submitted",
    submittedAt: Date.now(),
    startedAt: null,
    finishedAt: null,
    container: null,
    lastReportedTime: null,
    terminatedNormally: false,
    stopReason: null,
    detail: "",
  };
}

async function phasePlan(casesRoot: string): Promise<void> {
  const jobDir = join(casesRoot, JOB_ID);
  const source = join("/data2/kexiao/of8/rf-cases", "1D_advection");
  if (!existsSync(source)) {
    throw new Error(
      `reference case not found at ${source}; it is created by the realfluid-baseline-001 build`,
    );
  }
  await rm(jobDir, { recursive: true, force: true });
  await mkdir(jobDir, { recursive: true });
  await cp(source, jobDir, { recursive: true });

  const plan = makePlan(jobDir);
  const digest = planDigest(plan);
  await writeJobRecord(jobDir, { plan, state: emptyState(plan.jobId), planDigest: digest });

  // The runner is the exact command the plan describes, written to the job
  // directory so the host phase executes what was recorded rather than what it
  // is told at run time.
  const command = buildCommand(plan);
  await writeFile(
    join(jobDir, RUNNER),
    `#!/bin/bash\n# Generated by run-cfd-job.ts plan. Do not edit; the record\n# authenticates against this command's plan digest.\nset -e\ncd "$(dirname "$0")"\n${command} > ${LOG_FILE} 2>&1\n`,
    "utf8",
  );

  console.log(`ok plan recorded for ${plan.jobId} at ${jobDir}`);
  console.log(`   executable ${plan.profile.executable}`);
  console.log(`   budget ${plan.budgetSeconds}s, requested endTime ${plan.requestedEndTime}`);
  console.log(`   plan digest ${digest.slice(0, 16)}…`);
  console.log(`   runner ${join(jobDir, RUNNER)}`);
}

/**
 * The host executes the runner directly. There is no controller `run` phase on
 * the host, because the host has no Node and the controller is what records;
 * the runner is the plan's own command, and `assess` derives what happened
 * from the log it left.
 */

async function phaseAssess(jobDir: string): Promise<void> {
  const record = await readJobRecord(jobDir);
  if (!record) throw new Error(`no job record at ${jobDir}`);
  const { plan } = record;
  const state = await assessFromLog(jobDir, plan);

  const reached =
    state.state === "finished" &&
    state.terminatedNormally &&
    state.lastReportedTime !== null &&
    state.lastReportedTime >= plan.requestedEndTime * 0.999;

  console.log(`job ${plan.jobId}: ${state.state}`);
  console.log(`  ${state.detail}`);
  console.log(`  requested endTime ${plan.requestedEndTime}, reached ${state.lastReportedTime}`);
  console.log(
    reached
      ? "ok the job reached its requested physical time through the controller"
      : "note: the job did not reach its requested physical time",
  );
}

/**
 * Derives the terminal state from the log the solver left.
 *
 * The host executed the runner script; the controller cannot observe that
 * process and does not take the host's word for the outcome. The log is the
 * evidence, and this is all of it: whether the solver reported time steps, and
 * whether it ended normally.
 */
async function assessFromLog(
  jobDir: string,
  plan: CfdJobPlan,
): Promise<CfdJobState> {
  const logPath = join(jobDir, plan.logFile);
  const lastTime = await readLastTime(logPath);
  const normal = await readTerminatedNormally(logPath);
  const state: CfdJobState = {
    jobId: plan.jobId,
    state: "submitted",
    submittedAt: Date.now(),
    startedAt: null,
    finishedAt: Date.now(),
    container: null,
    lastReportedTime: lastTime,
    terminatedNormally: normal,
    stopReason: null,
    detail: "",
  };
  if (normal) {
    state.state = "finished";
    state.detail = "solver log ends with a normal End";
  } else if (lastTime !== null) {
    state.state = "failed";
    state.stopReason = "solver_error";
    state.detail = "solver reported time steps but did not end normally";
  } else {
    state.state = "failed";
    state.stopReason = "executor_error";
    state.detail = "no solver output found; the runner did not produce a log";
  }
  await updateJobState(jobDir, state);
  return state;
}

async function main(): Promise<void> {
  const phase = process.argv[2] ?? "all";
  // The case directory lives under the repository mount so both sides see it.
  const root = process.env.EVOCFD_HOST_ROOT ?? ".";
  const casesRoot = join(root, "runs", "cfd-cases");

  if (phase === "plan") {
    await phasePlan(casesRoot);
  } else if (phase === "run") {
    // The run happens on the host with the runner the plan wrote. This entry
    // point exists so the lifecycle is complete and testable where Node is
    // available, but the real execution path is the runner script itself.
    const jobDir = process.argv[3] ?? join(casesRoot, JOB_ID);
    const record = await readJobRecord(jobDir);
    if (!record) throw new Error(`no job record at ${jobDir}`);
    console.log(`runner for ${record.plan.jobId} is ${join(jobDir, RUNNER)}`);
    console.log("execute it on the host where the solver libraries live");
  } else if (phase === "assess") {
    const jobDir = process.argv[3] ?? join(casesRoot, JOB_ID);
    await phaseAssess(jobDir);
  } else {
    console.error("usage: run-cfd-job.ts plan|run|assess [job-dir]");
    process.exitCode = 2;
  }
}

await main();
