/**
 * Runs one real CFD job through the job-lifecycle primitive.
 *
 * Two phases, because the solver and the controller cannot run in the same
 * place. The controller is a Node toolchain in the campaign container; the
 * solver was built on the host against system gcc and system Open MPI and links
 * libmpi.so.40, which the container does not provide. Mounting the host
 * binaries into the container does not make them runnable there — the loader
 * error is genuine, and rebuilding the solver inside a container would be a
 * second, differently-identified build rather than a fix for this one.
 *
 * So the boundary is explicit and the two phases are separate processes:
 *
 *   plan    in the container: copies the case, records the plan, writes a runner
 *   run     on the host: executes the runner the plan wrote
 *   assess  in the container: derives the outcome from the receipt and the log
 *
 * The runner is generated by the shared backend in packages/controller/src/runner.ts,
 * so a generic job here and a prepared MASCOTTE attempt execute through the same
 * tested path with the same deadline, logging and receipt semantics. There is no
 * second shell template to drift out of agreement.
 *
 * Usage:
 *   node scripts/run-cfd-job.ts plan
 *   node scripts/run-cfd-job.ts run <job-dir>     # on the host
 *   node scripts/run-cfd-job.ts assess <job-dir>
 */
import { join } from "node:path";
import { mkdir, cp, rm, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";

import {
  buildArgv,
  planDigest,
  readJobRecord,
  readLastTime,
  readTerminatedNormally,
  RECORD_FILE,
  resolveProfile,
  updateJobState,
  writeJobRecord,
} from "../packages/controller/src/cfd-exec.ts";
import {
  assessExecution,
  buildRunnerScript,
  readReceiptFile,
} from "../packages/controller/src/runner.ts";
import type { CfdJobPlan, CfdJobState } from "../packages/controller/src/cfd-job.ts";

const JOB_ID = "1D-advection-001";
const RUNNER = "run.sh";
const LOG_FILE = "log.react";

function makeProfile(): ReturnType<typeof resolveProfile> {
  return resolveProfile({
    id: "of8-realfluid",
    executable: "/data2/kexiao/of8/rf-profile/bin/reactingFoam",
    executableSha256:
      "14fd124a0e46d043cdad5f9b6b8e26ed23d0778084d55c609e9665d58799007c",
    envFile: "/data2/kexiao/of8/rf-profile-env.sh",
    libraryPaths: [
      "/data2/kexiao/of8/rf-profile/lib",
      "/data2/kexiao/of8/OpenFOAM-8/platforms/linux64GccDPInt32Opt/lib",
    ],
    expectedProfileLibraries: [
      "libreactionThermophysicalModels.so",
      "libspecie.so",
      "libchemistryModel.so",
      "libcombustionModels.so",
    ],
  });
}

function makePlan(jobDir: string): CfdJobPlan {
  return {
    jobId: JOB_ID,
    profile: makeProfile(),
    caseDir: jobDir,
    args: [],
    budgetSeconds: 600,
    requestedEndTime: 0.002,
    ranks: 1,
    logFile: LOG_FILE,
  };
}

function emptyState(jobId: string): CfdJobState {
  return {
    jobId,
    state: "submitted",
    submittedAt: Date.now(),
    startedAt: null,
    finishedAt: null,
    container: null,
    lastReportedTime: null,
    terminatedNormally: false,
    stopReason: null,
    detail: "",
  };
}

/**
 * Records what will run before anything runs.
 *
 * A plan is a claim about the future; the record is what makes it checkable.
 * The digest covers the whole runtime identity — executable, env file, library
 * order — because the package ships libraries with stock-identical SONAMES and a
 * binary that loads the wrong one still runs, with the wrong physics.
 */
async function phasePlan(casesRoot: string): Promise<void> {
  const jobDir = join(casesRoot, JOB_ID);
  const source = join("/data2/kexiao/of8/rf-cases", "1D_advection");
  if (!existsSync(source)) {
    throw new Error(
      `reference case not found at ${source}; it is created by the realfluid-baseline-001 build`,
    );
  }
  // A prior attempt is preserved, not wiped. Reusing a job id would discard the
  // record of what that attempt did, and overwriting an existing job directory
  // is exactly the loss the write-once record exists to prevent. A new attempt
  // gets a new job id.
  if (existsSync(join(jobDir, RECORD_FILE))) {
    throw new Error(
      `a job record already exists at ${join(jobDir, RECORD_FILE)}; a prior attempt is preserved. Use a new job id.`,
    );
  }
  await rm(jobDir, { recursive: true, force: true });
  await mkdir(jobDir, { recursive: true });
  await cp(source, jobDir, { recursive: true });

  const plan = makePlan(jobDir);
  const digest = planDigest(plan);
  await writeJobRecord(jobDir, { plan, state: emptyState(plan.jobId), planDigest: digest });

  // The runner is written into the job directory so the host phase executes what
  // was recorded rather than what it is told at run time. Building it from the
  // plan's own argument vector keeps the deadline on the executable instead of
  // on a shell expression.
  const argv = buildArgv(plan.profile.executable, plan.args, plan.ranks);
  const runner = buildRunnerScript({
    jobId: plan.jobId,
    planDigest: digest,
    argv,
    envFile: plan.profile.envFile,
    budgetSeconds: plan.budgetSeconds,
    logFile: plan.logFile,
  });
  await writeFile(join(jobDir, RUNNER), runner, "utf8");

  console.log(`ok plan recorded for ${plan.jobId} at ${jobDir}`);
  console.log(`   executable ${plan.profile.executable}`);
  console.log(`   budget ${plan.budgetSeconds}s, requested endTime ${plan.requestedEndTime}`);
  console.log(`   plan digest ${digest.slice(0, 16)}…`);
  console.log(`   runner ${join(jobDir, RUNNER)}`);
}

/**
 * The host phase. There is no controller supervision this process: the runner
 * is the plan's own command, and the deadline and receipt are enforced inside
 * it. This entry point exists so the lifecycle is complete and testable where
 * the runner is available, but the real execution path is the runner itself.
 */
async function phaseRun(jobDir: string): Promise<void> {
  const record = await readJobRecord(jobDir);
  if (!record) throw new Error(`no job record at ${jobDir}`);
  console.log(`runner for ${record.plan.jobId} is ${join(jobDir, RUNNER)}`);
  console.log("execute it on the host where the solver libraries resolve");
}

/**
 * Derives the terminal state from the receipt and the log together.
 *
 * Neither source implies the other. The receipt records what the process did;
 * the log records what the solver computed. A log that ends in a normal End
 * does not override a receipt whose exit code is nonzero, and a missing receipt
 * is not a verified successful execution — it is an execution error, because a
 * runner that wrote no receipt either did not finish or is not the runner this
 * code expects.
 */
async function assessFromLog(
  jobDir: string,
  plan: CfdJobPlan,
): Promise<CfdJobState> {
  const logPath = join(jobDir, plan.logFile);
  const lastTime = await readLastTime(logPath);
  const normal = await readTerminatedNormally(logPath);
  const receipt = await readReceiptFile(join(jobDir, "execution-receipt.txt"));

  // The receipt must describe this plan, not whichever execution last happened
  // to leave a file in this directory.
  const verdict = assessExecution({
    receipt,
    solver: { lastTime, terminatedNormally: normal },
    requestedEndTime: plan.requestedEndTime,
    expectedJobId: plan.jobId,
    expectedPlanDigest: planDigest(plan),
  });

  const state: CfdJobState = {
    jobId: plan.jobId,
    state: verdict.state,
    submittedAt: Date.now(),
    startedAt: verdict.startedAt,
    finishedAt: verdict.finishedAt,
    container: null,
    lastReportedTime: lastTime,
    terminatedNormally: normal,
    stopReason: verdict.stopReason,
    detail: verdict.detail,
  };
  await updateJobState(jobDir, state);
  return state;
}

async function phaseAssess(jobDir: string): Promise<void> {
  const record = await readJobRecord(jobDir);
  if (!record) throw new Error(`no job record at ${jobDir}`);
  const { plan } = record;
  const state = await assessFromLog(jobDir, plan);

  console.log(`job ${plan.jobId}: ${state.state} (${state.stopReason ?? "reached"})`);
  console.log(`  ${state.detail}`);
  console.log(
    `  requested endTime ${plan.requestedEndTime}, last reported ${state.lastReportedTime}`,
  );
}

async function main(): Promise<void> {
  const phase = process.argv[2] ?? "all";
  // The case directory lives under the repository mount so that a job created
  // in the container is executable on the host without path translation.
  const root = process.env.EVOCFD_HOST_ROOT ?? ".";
  const casesRoot = join(root, "runs", "cfd-cases");

  if (phase === "plan") {
    await phasePlan(casesRoot);
  } else if (phase === "run") {
    const jobDir = process.argv[3] ?? join(casesRoot, JOB_ID);
    await phaseRun(jobDir);
  } else if (phase === "assess") {
    const jobDir = process.argv[3] ?? join(casesRoot, JOB_ID);
    await phaseAssess(jobDir);
  } else {
    console.error("usage: run-cfd-job.ts plan|run|assess [job-dir]");
    process.exitCode = 2;
  }
}

await main();
